services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: ecotrace
      POSTGRES_PASSWORD: ecotrace
      POSTGRES_DB: ecotrace
    ports:
      - "5432:5432"
    volumes:
      - ./.postgres-data:/var/lib/postgresql/data
