import { useMemo, useState } from "react";
import { Link, useParams } from "react-router-dom";
import { useQuery } from "@tanstack/react-query";
import { Download, Network, RefreshCw, Search, ShieldCheck } from "lucide-react";
import { api } from "../api";
import { Shell } from "../components/Shell";
import { StatusBadge } from "../components/StatusBadge";
import type { ClaimStatus } from "@ecotrace/shared";
import { EvidenceGraphView } from "../components/EvidenceGraphView";

const stages = ["resolving_entity", "discovering_claims", "decomposing_claims", "planning_queries", "searching_independent", "analyzing_news", "testing_scientific", "checking_products", "analyzing_trends", "normalizing_evidence", "building_graph", "calculating_integrity", "completed"];
const pct = (value: number | null | undefined) => `${Math.round(value ?? 0)}%`;

export function AuditPage() {
  const { id = "" } = useParams();
  const [filter, setFilter] = useState<ClaimStatus | "ALL">("ALL");
  const detail = useQuery({ queryKey: ["audit", id], queryFn: () => api.getAudit(id), enabled: Boolean(id), refetchInterval: (q) => q.state.data?.audit.status === "running" || q.state.data?.audit.status === "queued" ? 1500 : false });
  const status = useQuery({ queryKey: ["audit-status", id], queryFn: () => api.getStatus(id), enabled: Boolean(id), refetchInterval: detail.data?.audit.status === "completed" || detail.data?.audit.status === "failed" ? false : 1500 });
  const graph = useQuery({ queryKey: ["graph", id], queryFn: () => api.getGraph(id), enabled: Boolean(id) && detail.data?.audit.status !== "running" });
  const timeline = useQuery({ queryKey: ["timeline", id], queryFn: () => api.getTimeline(id), enabled: Boolean(id) && detail.data?.audit.status !== "running" });
  const trace = useQuery({ queryKey: ["trace", id], queryFn: () => api.getTrace(id), enabled: Boolean(id) && detail.data?.audit.status !== "running" });
  const claims = useMemo(() => (detail.data?.claims ?? []).filter((c) => filter === "ALL" || c.status === filter), [detail.data, filter]);
  if (detail.isLoading || !detail.data) return <Shell><div className="py-24 text-center text-mist">Loading investigation…</div></Shell>;
  const { audit, metrics, credits } = detail.data;
  const current = status.data?.stage ?? audit.stage;
  const progress = current === "completed" ? 100 : Math.max(5, Math.round((stages.indexOf(current) + 1) / stages.length * 100));
  async function download() { const file = await api.exportAudit(id); const blob = new Blob([file.markdown], { type: "text/markdown" }); const url = URL.createObjectURL(blob); const a = document.createElement("a"); a.href = url; a.download = file.filename; a.click(); URL.revokeObjectURL(url); }
  return <Shell mockMode={audit.mockMode}>
    <div className="space-y-6">
      <header className="flex flex-wrap items-end justify-between gap-4"><div><p className="font-mono text-xs tracking-[.25em] text-accent">AUDIT / {audit.mode.toUpperCase()}</p><h1 className="mt-2 text-3xl font-semibold">{audit.companyName}</h1><p className="mt-1 text-sm text-mist">{audit.status === "running" ? "Investigation in progress" : "Evidence review complete"} · {new Date(audit.createdAt).toLocaleString()}</p></div><div className="flex gap-2"><button className="focus-ring rounded border border-line px-3 py-2 text-sm" onClick={() => void detail.refetch()}><RefreshCw size={15} className="mr-2 inline" />Refresh</button><button className="focus-ring rounded border border-accent/40 px-3 py-2 text-sm text-accent" onClick={() => void download()}><Download size={15} className="mr-2 inline" />Export</button></div></header>
      {audit.status === "running" || audit.status === "queued" ? <section className="glass rounded-md p-4"><div className="flex justify-between text-xs text-mist"><span className="font-mono tracking-[.15em] text-accent">{current.replaceAll("_", " ").toUpperCase()}</span><span>{progress}%</span></div><div className="mt-3 h-1.5 overflow-hidden rounded bg-line"><div className="h-full bg-accent transition-all" style={{ width: `${progress}%` }} /></div><div className="mt-3 flex flex-wrap gap-2 text-xs text-mist">{status.data?.engines.map((engine) => <span key={engine.engine} className="rounded border border-line px-2 py-1">{engine.engine} · {engine.status}</span>)}</div></section> : null}
      <section className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{[["Claim integrity", metrics?.claimIntegrity, "text-accent"],["Evidence coverage", metrics?.evidenceCoverage, "text-white"],["Source independence", metrics?.sourceIndependence, "text-white"],["Evidence conflict", metrics?.evidenceConflict, "text-conflict"]].map(([label, value, color]) => <div className="glass rounded-md p-4" key={String(label)}><p className="text-xs uppercase tracking-[.12em] text-mist">{label}</p><p className={`mt-2 text-2xl font-semibold ${color}`}>{pct(Number(value))}</p></div>)}</section>
      <div className="grid gap-6 lg:grid-cols-[1.3fr_.7fr]"><section className="glass rounded-md p-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="font-mono text-xs tracking-[.2em] text-accent">CLAIM REGISTER</p><h2 className="mt-1 text-xl font-semibold">What the evidence says</h2></div><select aria-label="Filter claims" className="rounded border border-line bg-ink px-2 py-2 text-sm" value={filter} onChange={(e) => setFilter(e.target.value as ClaimStatus | "ALL")}><option value="ALL">All statuses</option><option value="SUPPORTED">Supported</option><option value="PARTIALLY_SUPPORTED">Partially supported</option><option value="EVIDENCE_CONFLICT">Evidence conflict</option><option value="INSUFFICIENT_EVIDENCE">Insufficient evidence</option></select></div><div className="mt-4 space-y-2">{claims.length ? claims.map((claim) => <Link key={claim.id} to={`/audit/${id}/claim/${claim.id}`} className="focus-ring block rounded border border-line p-4 transition hover:border-accent/50"><div className="flex flex-wrap justify-between gap-2"><span className="text-sm font-medium">{claim.text}</span><StatusBadge status={claim.status} /></div><div className="mt-3 flex gap-4 text-xs text-mist"><span>{claim.category}</span><span>Integrity {pct(claim.integrityScore)}</span><span>Specificity {pct(claim.specificityScore)}</span></div></Link>) : <p className="py-10 text-center text-sm text-mist">Claims will appear as the audit progresses.</p>}</div></section><aside className="space-y-6"><section className="glass rounded-md p-5"><p className="font-mono text-xs tracking-[.2em] text-accent">RUN TELEMETRY</p><div className="mt-4 space-y-3 text-sm"><div className="flex justify-between"><span className="text-mist">Evidence items</span><span>{metrics?.evidenceCount ?? 0}</span></div><div className="flex justify-between"><span className="text-mist">Sources</span><span>{metrics?.sourceCount ?? 0}</span></div><div className="flex justify-between"><span className="text-mist">Requests</span><span>{credits.used} used / {credits.remaining} left</span></div><div className="flex justify-between"><span className="text-mist">Cached</span><span>{credits.cached}</span></div></div></section><nav className="glass rounded-md p-5"><p className="font-mono text-xs tracking-[.2em] text-accent">INVESTIGATION VIEWS</p><div className="mt-4 grid gap-2 text-sm"><a className="focus-ring rounded border border-line px-3 py-2 hover:border-accent" href="#graph"><Network size={15} className="mr-2 inline" />Evidence graph ({graph.data?.nodes.length ?? 0} nodes)</a><a className="focus-ring rounded border border-line px-3 py-2 hover:border-accent" href="#timeline">Claim evolution ({timeline.data?.events.length ?? 0} events)</a><a className="focus-ring rounded border border-line px-3 py-2 hover:border-accent" href="#trace"><Search size={15} className="mr-2 inline" />Search trace ({trace.data?.requests.length ?? 0} requests)</a></div></nav></aside></div>
      <section id="graph" className="glass rounded-md p-5"><div className="flex items-center gap-2"><Network size={17} className="text-accent" /><h2 className="text-lg font-semibold">Evidence graph</h2></div><p className="mt-1 text-sm text-mist">{graph.data?.nodes.length ?? 0} entities linked by {graph.data?.edges.length ?? 0} evidence relationships. Open a claim to inspect the underlying chain.</p><div className="mt-4 flex flex-wrap gap-2">{graph.data?.nodes.slice(0, 24).map((node) => <span key={node.id} className="rounded border border-line px-2 py-1 text-xs"><span className="text-accent">{node.type}</span> · {node.label.slice(0, 70)}</span>)}</div></section>
      <section id="timeline" className="glass rounded-md p-5"><h2 className="text-lg font-semibold">Claim evolution</h2><div className="mt-4 space-y-2">{timeline.data?.events.length ? timeline.data.events.map((event) => <div key={event.id} className="border-l border-accent/50 pl-4 text-sm"><span className="font-mono text-xs text-accent">{event.eventDate ?? "DATE UNKNOWN"}</span><p>{event.text}</p></div>) : <p className="text-sm text-mist">No dated claim events were found.</p>}</div></section>
      <section id="trace" className="glass rounded-md p-5"><div className="flex items-center gap-2"><ShieldCheck size={17} className="text-accent" /><h2 className="text-lg font-semibold">SerpApi search trace</h2></div><div className="mt-4 overflow-x-auto"><table className="w-full min-w-[680px] text-left text-xs"><thead className="text-mist"><tr><th className="pb-2">Engine</th><th>Query</th><th>Status</th><th>Results</th><th>Credits</th></tr></thead><tbody>{trace.data?.requests.map((r) => <tr key={r.id} className="border-t border-line"><td className="py-2 text-accent">{r.engine}</td><td>{r.query}</td><td>{r.status}</td><td>{r.resultCount}</td><td>{r.cached ? "cached" : r.creditsUsed}</td></tr>)}</tbody></table></div></section>
      <section className="glass rounded-md p-5"><EvidenceGraphView graph={graph.data} /></section>
    </div>
  </Shell>;
}
